apiVersion: apps/v1
kind: Deployment
metadata:
  name: claims-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: claims-api
  template:
    metadata:
      labels:
        app: claims-api
    spec:
      containers:
        - name: claims-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
{{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
{{- end }}
