apiVersion: v1
kind: Service
metadata:
  name: claims-api
spec:
  type: NodePort
  selector:
    app: claims-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: 30203
      protocol: TCP
      name: http
