apiVersion: v1
kind: Service
metadata:
  name: policies-api
spec:
  type: NodePort
  selector:
    app: policies-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: 30202
      protocol: TCP
      name: http
