apiVersion: v1
kind: Service
metadata:
  name: referencedata-api
spec:
  type: NodePort
  selector:
    app: referencedata-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      nodePort: 30201
      protocol: TCP
      name: http
