-- Policies Service
USE PoliciesService;
GO -- Every GO separates the execution of every block of code

DROP TABLE Policy;
DROP TABLE PolicyHolder;
GO

IF OBJECT_ID('PolicyHolder', 'U') IS NULL
BEGIN
	CREATE TABLE PolicyHolder (
		id INT IDENTITY(1, 1) PRIMARY KEY,
		firstName VARCHAR(100) NOT NULL,
		lastName VARCHAR(100) NOT NULL,
		email VARCHAR(255) UNIQUE NOT NULL,
		phone VARCHAR(20),
		dateOfBirth DATE NOT NULL,
		regionCode VARCHAR(10) NOT NULL, -- Validated against Reference Data
		createdAt DATETIME DEFAULT GETUTCDATE(),
		updatedAt DATETIME
	);
END;
GO

CREATE OR ALTER TRIGGER trg_Update_PolicyHolder
ON PolicyHolder
AFTER UPDATE
AS
BEGIN
	SET NOCOUNT ON; -- Shutdown info messages like 'X rows affected'

	UPDATE p
		SET updatedAt = GETUTCDATE()
		FROM PolicyHolder p
		INNER JOIN inserted i ON p.id = i.id; -- Virtual table 'inserted'
END;
GO

IF OBJECT_ID('Policy', 'U') IS NULL
BEGIN
	CREATE TABLE Policy (
		id INT IDENTITY(1, 1) PRIMARY KEY,
		policyNumber VARCHAR(20) UNIQUE NOT NULL, -- Generated by backend
		policyHolderId INT NOT NULL, -- FK to PolicyHolder
		policyTypeCode VARCHAR(20) NOT NULL CHECK (policyTypeCode IN ('AVIATION', 'ENERGY', 'MARINE', 'CYBER', 'LIABILITY')), -- Validated against Reference Data
		coverageTypeCode VARCHAR(20) NOT NULL CHECK (coverageTypeCode IN ('FULL', 'PARTIAL', 'THIRD_PARTY', 'CATASTROPHIC')), --Validated against Reference Data
		coverageAmount decimal(18, 2) NOT NULL CHECK (coverageAmount > 0),
		premiumAmount decimal(18, 2) NOT NULL CHECK (premiumAmount > 0),
		startDate DATE NOT NULL,
		endDate DATE NOT NULL,
		status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE', 'EXPIRED', 'CANCELLED')),
		createdAt DATETIME DEFAULT GETUTCDATE(),
		updatedAt DATETIME,

		CONSTRAINT FK_PolicyHolder_Holder FOREIGN KEY (policyHolderId) REFERENCES PolicyHolder(id),
		CONSTRAINT CHK_Policy_Dates CHECK (endDate > startDate)
	);
END;
GO

CREATE OR ALTER TRIGGER trg_Update_Policy
ON Policy
AFTER UPDATE
AS
BEGIN
	SET NOCOUNT ON; -- Shutdown info messages like 'X rows affected'

	UPDATE p
		SET updatedAt = GETUTCDATE()
		FROM Policy p
		INNER JOIN inserted i ON p.id = i.id; -- Virtual table 'inserted'
END;
GO





-- Hacer un trigger que automaticamente cambie el estado de las pólizas a EXPIRED cuando la fecha actual sea mayor a la fecha de fin.